### ISSUE TITLE
address object not created by NIA 

### ISSUE THREAD

**Issue by devarshishah3** [findkim/terraform-consul-consul-nia#3]
I am using the following NIA tasks file: tasks.hcl and running 'consul-nia -config-dir tasks'
log_level = "info"

driver "terraform" {
  log = true
  required_providers {
    panos = {
      source = "PaloAltoNetworks/panos"
    }
  }
}

consul {
  address = "localhost:8500"
}

provider "panos" {
  alias = "panos1"
  hostname = "3.211.53.76"
  api_key = <left out for security>
}

provider "panos" {
  alias = "panos2"
  hostname = "54.152.201.95"
  api_key = <left out for security>
}

task {
  name = "Create_DAG_on_PANOS1"
  description = "Dynamic Address Groups based on service definition"
  source = "findkim/ngfw/panos"
  version = "0.0.1-beta4"
  providers = ["panos.panos1"]
  services = ["api", "web"]
  variable_files = ["/Users/devarshishah/Desktop/Environments/NIA-demo/tasks/user-demo.tfvars"]
}

task {
  name = "Create_DAG_on_PANOS2"
  description = "Dynamic Address Groups based on service definition"
  source = "findkim/ngfw/panos"
  version = "0.0.1-beta4"
  providers = ["panos.panos2"]
  services = ["web"]
  variable_files = ["/Users/devarshishah/Desktop/Environments/NIA-demo/tasks/user-demo.tfvars"]
}

Seeing the following error:

2020/09/27 21:56:41.059529 [INFO] running Terraform command: /Users/devarshishah/Desktop/Environments/NIA-demo/terraform apply -no-color -auto-approve -input=false -var-file=/Users/devarshishah/Desktop/Environments/NIA-demo/tasks/user-demo.tfvars -var-file=terraform.tfvars -lock=true -parallelism=10 -refresh=true
module.Create_DAG_on_PANOS1.panos_administrative_tag.tag: Refreshing state... [id=vsys1:consul-nia]
module.Create_DAG_on_PANOS1.panos_application_object.consul: Refreshing state... [id=vsys1:consul-services]
module.Create_DAG_on_PANOS1.panos_address_group.addresses: Refreshing state... [id=vsys1:Consul NIA services]
module.Create_DAG_on_PANOS1.panos_security_rule_group.rules: Refreshing state... [id=vsys1:1:Log default deny:V2ViIHRvIEFQSQ==]
module.Create_DAG_on_PANOS1.panos_address_object.addrObj["api2"]: Creating...
module.Create_DAG_on_PANOS1.panos_address_object.addrObj["web"]: Creating...
module.Create_DAG_on_PANOS1.panos_address_object.addrObj["api1"]: Creating...

Error:  consul-service-api2 -> tag is invalid

  on .terraform/modules/Create_DAG_on_PANOS1/main.tf line 26, in resource "panos_address_object" "addrObj":
  26: resource "panos_address_object" "addrObj" {

Error:  consul-service-api1 -> tag is invalid

  on .terraform/modules/Create_DAG_on_PANOS1/main.tf line 26, in resource "panos_address_object" "addrObj":
  26: resource "panos_address_object" "addrObj" {

Error:  consul-service-web -> tag is invalid

  on .terraform/modules/Create_DAG_on_PANOS1/main.tf line 26, in resource "panos_address_object" "addrObj":
  26: resource "panos_address_object" "addrObj" {

2020/09/27 21:56:46.583843 [ERR] (cli) error running controller: [ERR] (controller.readwrite): could not apply: Error tf-apply for 'Create_DAG_on_PANOS1': attempt #1 failed '
Error:  consul-service-api2 -> tag is invalid

  on .terraform/modules/Create_DAG_on_PANOS1/main.tf line 26, in resource "panos_address_object" "addrObj":
  26: resource "panos_address_object" "addrObj" {

Error:  consul-service-api1 -> tag is invalid

  on .terraform/modules/Create_DAG_on_PANOS1/main.tf line 26, in resource "panos_address_object" "addrObj":
  26: resource "panos_address_object" "addrObj" {

Error:  consul-service-web -> tag is invalid

  on .terraform/modules/Create_DAG_on_PANOS1/main.tf line 26, in resource "panos_address_object" "addrObj":
  26: resource "panos_address_object" "addrObj" {

**Comment by findkim** [comment]
It looks like the referenced tags applied to the address objects do not already exist and need to be created outside of the module on PANOS. https://github.com/findkim/terraform-panos-ngfw/blob/master/variables.tf#L31
